# Generated by Django 5.0.3 on 2024-03-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliGestMedical', '0002_utilisateur_is_active_utilisateur_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
