# Generated by Django 5.0.3 on 2024-03-06 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apliGestMedical', '0003_utilisateur_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.CharField(choices=[('Hopital1', 'Hôpital 1'), ('Hopital2', 'Hôpital 2')], max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('marital_status', models.CharField(choices=[('Celibataire', 'Célibataire'), ('Couple', 'Couple')], max_length=50)),
                ('adresse', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('profession', models.CharField(choices=[('Medecin', 'Médecin'), ('Ingenieur', 'Ingénieur'), ('Informaticien', 'Informaticien'), ('Secretair', 'Secrétair'), ('Agriculteu', 'Agriculteur'), ('Artisant', 'Artisant'), ('Professeur', 'Professeur'), ('Entrepreneur', 'Entrepreneur')], default='Autre', max_length=100)),
                ('type_consultation', models.CharField(choices=[('Nourrisson', 'Nourrisson'), ('Enfant', 'Enfant'), ('Adolescent', 'Adolescent'), ('Adulte', 'Adulte'), ('Personne agee', 'Personne âgée'), ('Femme enceinte', 'Femme enceinte')], max_length=50)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Féminin')], max_length=50)),
                ('description', models.TextField()),
                ('nature_assistance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentJustificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents_justificatifs/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rendezvous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='apliGestMedical.rendezvous')),
            ],
        ),
    ]
